### ISSUE TITLE
All Player Sessions Timing Out

### ISSUE THREAD

**Issue by cashcache** [YetiTech-Studios/UE4GameLiftClientSDK#25]
I'm not sure what is causing this, but after successfully establishing a new player session and connecting the client to the server, the Player Session Status in the Game Lift console shows it times out after 1 min. This happens even though the client is in the game and things seem to be working property. This happens 100% of the time and I never see an Active status.

After the Activate() gets called on the player session, is there another call I need to make to confirm the reservation, or is pushing the PlayerController to the returned IP and Port enough?

**Comment by chris-gong** [comment]
On the server side, you have to either accept or deny the incoming player session. I recommend passing the player session id as a parameter via openlevel so that in your server's gamemode class' prelogin method you can parse through the options to get this player session id. Then, from there, you can choose to accept or deny the player session.

**Comment by cashcache** [comment]
Yep, that was it. Thanks for the assist. I still have a lot of learning to do, but I'm now running in the cloud!
